services:
  - type: web
    name: kisan-setu-onion-grader
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MOCK_MODEL
        value: "true"
      - key: SMS_MOCK
        value: "true"
      - key: SECRET_KEY
        value: sih2026_kisan_setu_secret_key_agrigrade_demo
      - key: PUBLIC_BASE_URL
        fromService:
          type: web
          name: kisan-setu-onion-grader
          property: host
